import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "@/component/Wrapper";
import Navbar from "@/component/layout/Navbar";
import Sidebar from "@/component/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Website SPP ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`h-full ${inter.className}`}>
        <Wrapper>
          <div className="grid grid-cols-5 grid-rows-[75px_1fr_1fr] min-h-full">
            <Navbar />

            <div className="row-span-4 row-start-2">
              <Sidebar />
            </div>

            <div className="col-span-4 row-span-4 row-start-2 p-4 bg-gray-100 ">
              {children}
            </div>
          </div>
        </Wrapper>
      </body>
    </html>
  );
}
